GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Syihabuddin",
    "email": "udin123@gmail.com",
    "provinsi": "Jawa Timur",
    "kota": "Banyuwangi",
    "password": "udin123456",
    "confPassword": "udin123456"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "udin@gmail.com",
    "password": "udin123"
}
###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiaW9maSIsImVtYWlsIjoidWRpbkBlbWFpbC5jb20iLCJpYXQiOjE3MDEyMjIwMzksImV4cCI6MTcwMTIyMjA1NH0.snM5R79o0nppKWlsV5b5g38XHnbcUGxaRgGTQsucqxY

###

GET http://localhost:3000/token

###
DELETE http://localhost:3000/logout

###
GET http://localhost:3000/article

###
POST http://localhost:3000/article
Content-Type: application/json

{
    "title": "Cara menanam Jagung dengan cuaca yang ekstrim",
    "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}