GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "iofi",
    "email": "udin@email.com",
    "provinsi": "Jawa Timur",
    "kota": "Banyuwangi",
    "password": "udin123",
    "confPassword": "udin123"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "udin@email.com",
    "password": "udin123"
}
###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiaW9maSIsImVtYWlsIjoidWRpbkBlbWFpbC5jb20iLCJpYXQiOjE3MDExNTc0MTksImV4cCI6MTcwMTE1NzQzNH0.AmWqu5OOIqotz7HVflF0k9UN3a2Lpfl2yaxMQdg8qj4

###

GET http://localhost:3000/token

###
DELETE http://localhost:3000/logout