GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Syihabuddin",
    "email": "astaganaga@gmail.com",
    "provinsi": "Jawa Timur",
    "kota": "Banyuwangi",
    "password": "udin123456",
    "confPassword": "udin123456"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "iofi@gmail.com",
    "password": "Deesnut1."
}
###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiaW9maSIsImVtYWlsIjoiaW9maUBnbWFpbC5jb20iLCJwcm92aW5zaSI6Ikphd2FUaW11ciIsImtvdGEiOiJLb3RhIE1hbGFuZyIsImlhdCI6MTcwMjUyNDE2OSwiZXhwIjoxNzAyNTI0MTg5fQ.MhpQw1KDcITVNlOPCT9Q2RBiyc01TMUnd8L_5tOAOaQ

###

GET http://localhost:3000/token

###
DELETE http://localhost:3000/logout

###
GET http://localhost:3000/note

###
POST http://localhost:3000/note
Content-Type: application/json

{
    "userId": 2,
    "tanaman": "Rose",
    "jumlah": 10.5,
    "tanggal": "2023-12-14T12:00:00Z"
}